#!/bin/sh

cd ../..

remove_project_run_files() {
   find . -name "ParaView_*" -print | xargs /bin/rm -rf
   find . -name "Report_*" -print | xargs /bin/rm -rf
   find . -name "*_FarField.csv" -print | xargs /bin/rm -rf
   find . -name "junk*" -print | xargs /bin/rm -rf
   find . -name "*_attributes.csv" -print | xargs /bin/rm -rf
   find . -name "temp_*" -print | xargs /bin/rm -rf
   find . -name "*_results.csv" -print | xargs /bin/rm -rf
   find . -name "*_results.txt" -print | xargs /bin/rm -rf
   find . -name "*_results.log" -print | xargs /bin/rm -rf
}

CURRENTDATE=`date +"%m-%d-%Y"`

cd OpenParEM/src
make distclean
cd ../..

cd OpenParEM/regression
   remove_project_run_files
   rm -Rf OpenParEM3D/WR90/straight-adaptive/refined_straight.msh
cd ../..

cd OpenParEM/tutorials
   remove_project_run_files
cd ../..

# source code distribution - also a full backup with executables removed
tar --exclude='.git' --exclude='OpenParEM/bin' --exclude='OpenParEM/etc' --exclude='OpenParEM/include' --exclude='OpenParEM/lib' --exclude='OpenParEM/sbin' --exclude='OpenParEM/share' -zcf OpenParEM_${CURRENTDATE}.tar.gz OpenParEM

# binary distribution - without external packages, source code, and include files
tar --exclude='.git' --exclude='OpenParEM/external_packages' --exclude='OpenParEM/include' --exclude='OpenParEM/sbin' --exclude='OpenParEM/src' -zcf OpenParEM_bin_${CURRENTDATE}.tar.gz OpenParEM

