#!/bin/sh

VERSION=2.1.0

cd ../..

remove_project_run_files() {
   find . -name "ParaView_*" -print | xargs /bin/rm -rf
   find . -name "Report_*" -print | xargs /bin/rm -rf
   find . -name "*_FarField.csv" -print | xargs /bin/rm -rf
   find . -name "junk*" -print | xargs /bin/rm -rf
   find . -name "*_attributes.csv" -print | xargs /bin/rm -rf
   find . -name "temp_*" -print | xargs /bin/rm -rf
   find . -name "*_results.csv" -print | xargs /bin/rm -rf
   find . -name "*_results.txt" -print | xargs /bin/rm -rf
   find . -name "*_results.log" -print | xargs /bin/rm -rf
}

CURRENTDATE=`date +"%m-%d-%Y"`

cd OpenParEM-${VERSION}/src
make distclean
cd ../..

cd OpenParEM-${VERSION}/regression
   remove_project_run_files
   rm -Rf OpenParEM-${VERSION}3D/WR90/straight-adaptive/refined_straight.msh
cd ../..

cd OpenParEM-${VERSION}/tutorials
   remove_project_run_files
cd ../..


# source code distribution - also a full backup with executables removed

echo "Building OpenParEM-${VERSION}_${CURRENTDATE}.tar.gz"

tar --exclude=".git" --exclude="OpenParEM-${VERSION}/bin" --exclude="OpenParEM-${VERSION}/etc" --exclude="OpenParEM-${VERSION}/include" --exclude="OpenParEM-${VERSION}/lib" --exclude="OpenParEM-${VERSION}/lib64" --exclude="OpenParEM-${VERSION}/sbin" --exclude="OpenParEM-${VERSION}/share" --exclude="OpenParEM-${VERSION}/libexec" -zcf OpenParEM-${VERSION}_${CURRENTDATE}.tar.gz OpenParEM-${VERSION}



# binary distribution - without external packages, source code, and include files

echo "Building OpenParEM-${VERSION}-bin_${CURRENTDATE}.tar.gz"

tar --exclude=".git" --exclude="OpenParEM-${VERSION}/external_packages" --exclude="OpenParEM-${VERSION}/include" --exclude="OpenParEM-${VERSION}/bin" --exclude="OpenParEM-${VERSION}/sbin" --exclude="OpenParEM-${VERSION}/src" --exclude="OpenParEM-${VERSION}/libexec" -cf OpenParEM-${VERSION}-bin_${CURRENTDATE}.tar OpenParEM-${VERSION}

tar -rf OpenParEM-${VERSION}-bin_${CURRENTDATE}.tar OpenParEM-${VERSION}/bin/OpenParEM2D* OpenParEM-${VERSION}/bin/OpenParEM3D* OpenParEM-${VERSION}/bin/process2D* OpenParEM-${VERSION}/bin/process3D* OpenParEM-${VERSION}/bin/simplify2D* OpenParEM-${VERSION}/bin/simplify3D* OpenParEM-${VERSION}/bin/builder* OpenParEM-${VERSION}/bin/mpirun OpenParEM-${VERSION}/bin/ort*

gzip OpenParEM-${VERSION}-bin_${CURRENTDATE}.tar

